<?php

/** @var \Magento\Backend\Block\Cache\Permissions|null $permissions */
$permissions = $block->getData('permissions');
?>
<?php if ($permissions && $permissions->hasAccessToAdditionalActions()): ?>
    <div class="additional-cache-management">
        <h2>
            <span><?= $block->escapeHtml(__('Limpeza de cache de URLs')); ?></span>
        </h2>
        <p>
            <textarea name="purge_url"></textarea>
            <span><?= $block->escapeHtml(__('Digite as URLs para a limpeza')); ?></span>
        </p>
    </div>
<?php endif; ?>
